const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {createServer}=require('../server/viewer-server');
(async()=>{
 const server=createServer('.');await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],requests=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
  const base={schema_version:1,session:'score',sequence:1,observed_at:Date.now()/1000,available:true,phase:'SELECTING_HAND',mod_version:'1.5.0',scoring_context:{},hand:{cards:[{key:'c_base',rank:'Ace',suit:'Spades',visible:true,selected:true,slot:1}]},poker_hands:{'High Card':{level:1,chips:5,mult:1}},jokers:{cards:[{key:'j_joker',set:'Joker',visible:true,score_vars:{1:4},description:'+4 Mult'}]}};
  let response={state:base,stale:false,directory:'fixture'};
  await page.route('**/state',r=>r.fulfill({json:response}));
  await page.goto('http://127.0.0.1:'+server.address().port);
  await page.waitForFunction(()=>document.querySelector('.predicted-score')?.textContent==='80');
  assert.equal(await page.title(),'Balatro Observer v1.5.0');
  assert.deepEqual(await page.evaluate(()=>[value(1.234567),value(12),el('p','X1.234567 Mult, +0.30000000004 Mult').textContent,el('p','v1.5.0').textContent]),['1.23','12','X1.23 Mult, +0.30 Mult','v1.5.0']);
  assert.equal(await page.evaluate(()=>value(-2.71828)),'-2.72');
  assert.equal(await page.locator('#nav-reference').count(),0);
  await page.locator('#nav-hand').click();assert.equal(await page.locator('.predicted-score').textContent(),'80');
  if(process.env.SCORE_SCREENSHOT_PATH)await page.screenshot({path:process.env.SCORE_SCREENSHOT_PATH,fullPage:true});
  response={...response,state:{...base,sequence:2,hand:{cards:[{...base.hand.cards[0],selected:false}]}}};
  await page.waitForFunction(()=>document.querySelector('#score-preview').textContent.includes('Last selected hand'));
  assert.equal(await page.locator('.predicted-score').textContent(),'80');
  response={...response,state:{...base,phase:'HAND_PLAYED',sequence:3,hand:{cards:[]}}};
  await page.waitForFunction(()=>document.querySelector('#raw').textContent.includes('HAND_PLAYED'));
  assert.equal(await page.locator('.predicted-score').textContent(),'80');
  response={...response,stale:true};
  await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Last preview'));
  assert.equal(await page.locator('.predicted-score').textContent(),'80');
  response={state:{...base,available:false,sequence:4},stale:false};
  await page.waitForFunction(()=>document.querySelector('#raw').textContent.includes('"available": false'));
  assert.equal(await page.locator('.predicted-score').textContent(),'80');
  response={state:{...base,sequence:5,hand:{cards:[{...base.hand.cards[0],rank:'King'}]}},stale:false};
  await page.waitForFunction(()=>document.querySelector('.predicted-score')?.textContent==='75');
  response={state:{...base,sequence:6,session:'new-session',hand:{cards:[]}},stale:false};
  await page.waitForFunction(()=>document.querySelector('.predicted-score')===null);
  assert.ok(requests.every(url=>url.startsWith('http://127.0.0.1:')));
  assert.deepEqual(errors,[]);
  console.log('PASS: live selection score, overview/hand, no library, renamed title, score retention across play/staleness/transitions, replacement and session reset and local-only calculator');
 }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
