const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const net=require('node:net');
const {spawn}=require('node:child_process');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const root=path.resolve(__dirname,'..'),dir=path.join(root,'work','server-fixtures');await fs.mkdir(dir,{recursive:true});
 const source=await fs.readFile(path.join(root,'work','test-recording.jsonl'),'utf8');
 const journal=source+JSON.stringify({network:{action:'enemyLocation',location:'loc_shop-bl_big'},after_action:13})+'\n'+JSON.stringify({opponent:{nemesis_location:'Shop',nemesis_location_blind:'bl_big',nemesis_score:'4200'},after_action:13})+'\n',filename='run-123-456-1.jsonl';
 await fs.writeFile(path.join(dir,filename),journal);
 const portProbe=net.createServer();await new Promise(r=>portProbe.listen(0,'127.0.0.1',r));const port=portProbe.address().port;await new Promise(r=>portProbe.close(r));
 const child=spawn(path.join(process.env.SystemRoot,'System32/WindowsPowerShell/v1.0/powershell.exe'),['-NoProfile','-ExecutionPolicy','Bypass','-File',path.join(root,'server/start-recorder.ps1'),'-Server','-Port',String(port),'-StateDirectory',dir],{windowsHide:true});
 let output='',browser;child.stderr.on('data',data=>output+=data);
 try{
  const base='http://127.0.0.1:'+port;let healthy=false;
  for(let i=0;i<100;i++){try{healthy=(await(await fetch(base+'/health')).json()).app==='BalatroActionRecorder';if(healthy)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  assert.ok(healthy,output);
  const list=await(await fetch(base+'/recordings')).json();assert.equal(list.recordings[0].file,filename);
  const response=await fetch(base+'/export?file='+filename),exported=await response.text();
  assert.match(response.headers.get('content-disposition'),/attachment/);
  assert.match(response.headers.get('content-type'),/text\/plain/);
  assert.equal(exported.split('\n').filter(line=>/^\d+\./.test(line)).length,13);
  assert.ok(exported.includes('2. discard [hand]: [("Ace of Spades", 2), ("King of Spades", 3)]'));
  assert.ok(exported.includes('("Queen of Spades", 3)'));
  assert.ok(exported.includes('("face-down card", 3)'));
  assert.match(exported,/after action 13.*seal=Red/);
  assert.ok(!exported.includes('[card '));
  assert.ok(!exported.includes('SECRET'));
  assert.ok(!exported.includes('edition={}'));
  assert.match(exported,/Run setup:.*"seed":"REPLAY42"/);
  assert.match(exported,/Run setup:.*"deck":"b_red"/);
  assert.match(exported,/before action 1 \| hand:.*Ace of Spades.*, 1/);
  assert.match(exported,/after action 1 \| hand: \[\("Ace of Spades", 1\)\] \| settled/);
  assert.equal(exported.split('before action ').length-1,4);
  assert.equal(exported.split(/after action \d+ \| hand:/).length-1,4);
  assert.ok(!exported.includes('Replay compatibility:'));
  assert.match(exported,/Multiplayer event: .*enemyLocation/);
  assert.match(exported,/Multiplayer after action 13: .*4200/);
  assert.ok(!exported.includes("Replay header:"));
  assert.ok(!exported.includes("Replay record:"));
  await fs.writeFile(path.join(root,'work','exported-v2.txt'),exported);
  assert.equal((await(await fetch(base+'/health')).json()).version,'2.0.2');
  for(const token of ['play','discard','buy','sell','reroll','use','pack_pick','pack_skip','reorder','select_blind','skip_blind'])assert.ok(exported.includes('. '+token));
  const pendingJournal=journal+JSON.stringify({cards:{},action:{n:14,type:'play',hand_before:[]}})+'\n';
  await fs.writeFile(path.join(dir,filename),pendingJournal);
  assert.match(await(await fetch(base+'/export?file='+filename)).text(),/after action 14 \| hand: unavailable/);
  const emptyHand={cards:{},observation:{after_action:14,areas:{},hand_after:[],hand_boundary:'settled'}};
  await fs.appendFile(path.join(dir,filename),JSON.stringify(emptyHand)+'\n');
  const emptyExport=await(await fetch(base+'/export?file='+filename)).text();
  assert.match(emptyExport,/after action 14 \| hand: \[\] \| settled/);
  assert.ok(!emptyExport.includes('unavailable'));
  await fs.writeFile(path.join(dir,filename),journal);
  const oldInventory={cards:{99:{name:'Unrelated Joker',key:'j_unrelated'}},observation:{after_action:13,areas:{jokers:[{card:'99',index:1,instance:99}]}}};
  await fs.writeFile(path.join(dir,filename),journal+JSON.stringify(oldInventory)+'\n');
  const inventoryExport=await(await fetch(base+'/export?file='+filename)).text();
  assert.ok(!inventoryExport.includes('changed [jokers]:'));
  await fs.writeFile(path.join(dir,filename),journal);
  await fs.appendFile(path.join(dir,filename),'{"unfinished":');
  assert.match(await(await fetch(base+'/export?file='+filename)).text(),/incomplete final journal entry ignored/);
  await fs.writeFile(path.join(dir,filename),journal+'invalid complete line\n');
  assert.equal((await fetch(base+'/export?file='+filename)).status,422);
  await fs.writeFile(path.join(dir,filename),journal);
  const replayEvent={cards:{},action:{n:14,type:'ready_blind',value:'1'}};
  await fs.writeFile(path.join(dir,filename),journal+JSON.stringify(replayEvent)+'\n');
  assert.match(await(await fetch(base+'/export?file='+filename)).text(),/14\. ready_blind 1/);
  await fs.writeFile(path.join(dir,filename),journal);
  assert.equal((await fetch(base+'/export?file=..%2FREADME.md')).status,422);
  assert.equal((await fetch(base+'/README.md')).status,404);
  assert.equal((await fetch(base+'/recordings',{method:'POST'})).status,405);
  browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE});const page=await browser.newPage({acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base);await page.locator('.recording').waitFor();
  assert.match(await page.locator('main').textContent(),/full visible hand before and after/);
  for(const route of ['/recorder.css','/recorder.js'])assert.equal((await fetch(base+route)).status,200);
  const downloadPromise=page.waitForEvent('download');await page.locator('#export-latest').click();const download=await downloadPromise;
  assert.equal(download.suggestedFilename(),'run-123-456-1.txt');
  assert.equal(await fs.readFile(await download.path(),'utf8'),exported);
  for(const width of [1440,390]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
  await page.screenshot({path:path.join(root,'work','export-page.png'),fullPage:true});
  assert.equal((await fetch(base+'/remove?file='+filename,{method:'POST'})).status,403);
  assert.equal((await fetch(base+'/remove?file=..%2FREADME.md',{method:'POST',headers:{'X-Recorder-Action':'remove'}})).status,422);
  page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('button',{name:'Remove',exact:true}).click();
  assert.equal(await page.locator('.recording').count(),1);
  page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Remove',exact:true}).click();
  await page.locator('#empty').waitFor({state:'visible'});
  assert.equal((await(await fetch(base+'/recordings')).json()).recordings.length,0);
  assert.equal(await fs.readFile(path.join(dir,filename),'utf8'),journal);
  await fs.unlink(path.join(dir,filename+'.removed'));
  assert.deepEqual(errors,[]);
  console.log('PASS: 11 tokens, readable identities and property changes, complete and interrupted journal export, corruption refusal, path isolation, real browser text download and mobile layout');
 }finally{if(browser)await browser.close();child.kill();await new Promise(r=>child.exitCode!==null?r():child.once('exit',r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
